name = "Dihedral"
version = "0.1.0"
defaultTargets = ["dihedral"]

[[lean_lib]]
name = "Dihedral"

[[lean_exe]]
name = "dihedral"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.24.0"