name = "Dihedral"
version = "0.1.0"
defaultTargets = ["dihedral"]

[[lean_lib]]
name = "Dihedral"

[[lean_exe]]
name = "dihedral"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0"
[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
